// src/components/PostCard.tsx
import { Link } from "react-router-dom";
import { MessageCircle } from "lucide-react";
import { PostWithThread } from "@/types/post";
import { formatDate } from "@/lib/posts";
import { MarkdownRenderer } from "./MarkdownRenderer";
import { PostImages } from "./PostImages";
import { cn } from "@/lib/utils";

interface PostCardProps {
  post: PostWithThread;
  showThreadLink?: boolean;
  className?: string;
}

export function PostCard({ post, showThreadLink = true, className }: PostCardProps) {
  return (
    <article
      className={cn(
        "p-4 sm:p-5 border-b border-border transition-theme hover:bg-muted/30 animate-fade-in",
        className
      )}
    >
      <div className="flex gap-3">
        {/* Avatar placeholder - olive accent */}
        <div className="flex-shrink-0">
          <div className="w-10 h-10 sm:w-12 sm:h-12 rounded-full bg-primary/20 flex items-center justify-center">
            <span className="text-primary font-medium text-sm sm:text-base">J</span>
          </div>
        </div>

        <div className="flex-1 min-w-0">
          {/* Header */}
          <div className="flex items-center gap-2 flex-wrap">
            <span className="font-medium text-foreground">Journal</span>
            <span className="text-muted-foreground">·</span>
            <time className="text-muted-foreground text-sm" dateTime={post.createdAt}>
              {formatDate(post.createdAt)}
            </time>
          </div>

          {/* Thread badge */}
          {showThreadLink && post.thread && (
            <Link
              to={`/thread/${post.threadId}`}
              className="inline-flex items-center gap-1.5 mt-1.5 px-2 py-0.5 bg-primary/10 text-primary text-xs rounded-full hover:bg-primary/20 transition-colors"
            >
              <MessageCircle size={12} />
              <span>{post.thread.title}</span>
              {post.threadOrder && (
                <span className="text-primary/70">#{post.threadOrder}</span>
              )}
            </Link>
          )}

          {/* Content */}
          <div className="mt-2 text-foreground">
            <MarkdownRenderer content={post.content} />
          </div>

          {/* Images */}
          {post.images.length > 0 && (
            <PostImages images={post.images} className="mt-3" />
          )}
        </div>
      </div>
    </article>
  );
}

// src/lib/features/post/PostCard.svelte
<script lang="ts">
	import type { Post } from '$lib/shared/types';
	import { resolve } from '$app/paths';
	import Renderer from '$lib/features/markdown/Renderer.svelte';
	import PostImages from './PostImages.svelte';
	import PostActions from './PostActions.svelte';
	import Footnotes from './Footnotes.svelte';
	import PostHeader from './PostHeader.svelte';
	import { cn } from '$lib/utils';
	import { goto } from '$app/navigation';

	type ValidHref = `/post/${string}` | `/thread/${string}/${string}`;

	let {
		post,
		href,
		showActions = true,
		class: className
	}: {
		post: Post;
		href?: ValidHref;
		showActions?: boolean;
		class?: string;
	} = $props();
</script>

<article
	class={cn(
		'transition-theme animate-fade-in border-b border-border p-4 hover:bg-muted/30 sm:p-5',
		className
	)}
>
	<button
		role="link"
		onclick={() => href && goto(resolve(href))}
		class={cn('grid grid-cols-[auto_1fr] gap-x-3 text-left', href && 'cursor-pointer')}
	>
		<PostHeader createdAt={post.createdAt.toISOString()} />

		<div class="col-start-2 min-w-0">
			<!-- Content -->
			<div class="text-foreground">
				<Renderer content={post.content} />
			</div>

			<!-- Footnotes -->
			{#if post.footnotes}
				<Footnotes footnotes={post.footnotes} prefix={post.id} order={post.footnotes_order} />
			{/if}

			<!-- Images -->
			{#if post.images?.length > 0}
				<PostImages images={post.images} class="mt-3" />
			{/if}

			<!-- Actions -->
			{#if showActions}
				<PostActions postId={post.id} initialLikes={post.likes ?? 0} />
			{/if}

			<!-- Tags -->
			{#if post.tags?.length > 0}
				<div class="mt-3 flex flex-wrap gap-1.5">
					{#each post.tags as tag (tag)}
						<span
							class="inline-flex items-center rounded-md bg-muted px-2 py-0.5 text-xs text-muted-foreground"
						>
							#{tag}
						</span>
					{/each}
				</div>
			{/if}
		</div>
	</button>
</article>
