// src/lib/components/Header.svelte
<script lang="ts">
	import { Leaf } from '@lucide/svelte';
	import ThemeToggle from './ThemeToggle.svelte';
	import SearchFilter from './SearchFilter.svelte';
	import UserMenu from './UserMenu.svelte';

	let {
		onSearch,
		showSearch = true
	} = $props<{
		onSearch?: (query: string) => void;
		showSearch?: boolean;
	}>();
</script>

<header
	class="bg-background/80 border-border sticky top-0 z-50 border-b backdrop-blur-md transition-colors"
>
	<div class="mx-auto flex h-14 max-w-2xl items-center justify-between px-4">
		<a href="/" class="flex items-center gap-2 transition-opacity hover:opacity-80">
			<div class="bg-primary flex h-8 w-8 items-center justify-center rounded-full">
				<Leaf size={18} class="text-primary-foreground" />
			</div>
			<span class="text-foreground hidden text-lg font-semibold sm:block"> Journal </span>
		</a>

		<div class="flex items-center gap-2">
			{#if showSearch && onSearch}
				<SearchFilter {onSearch} />
			{/if}
			<ThemeToggle />
			<UserMenu />
		</div>
	</div>
</header>

// src/components/Header.tsx
import { Link } from "react-router-dom";
import { Leaf } from "lucide-react";
import { ThemeToggle } from "./ThemeToggle";
import { SearchFilter } from "./SearchFilter";
import { UserMenu } from "./UserMenu";

interface HeaderProps {
  onSearch?: (query: string) => void;
  showSearch?: boolean;
}

export function Header({ onSearch, showSearch = true }: HeaderProps) {
  return (
    <header className="sticky top-0 z-50 bg-background/80 backdrop-blur-md border-b border-border transition-theme">
      <div className="max-w-2xl mx-auto px-4 h-14 flex items-center justify-between">
        <Link to="/" className="flex items-center gap-2 hover:opacity-80 transition-opacity">
          <div className="w-8 h-8 rounded-full bg-primary flex items-center justify-center">
            <Leaf size={18} className="text-primary-foreground" />
          </div>
          <span className="font-semibold text-lg text-foreground hidden sm:block">
            Journal
          </span>
        </Link>

        <div className="flex items-center gap-2">
          {showSearch && onSearch && <SearchFilter onSearch={onSearch} />}
          <ThemeToggle />
          <UserMenu />
        </div>
      </div>
    </header>
  );
}
