// src/lib/components/ThemeToggle.svelte
<script lang="ts">
	import { Moon, Sun } from '@lucide/svelte';
	import { theme } from '$lib/hooks/theme.svelte';
	import * as Button from '$lib/components/ui/button';
</script>

<Button.Root
	variant="ghost"
	size="icon"
	onclick={() => theme.toggleTheme()}
	class="text-muted-foreground hover:text-foreground hover:bg-muted"
	aria-label={`Switch to ${theme.theme === 'dark' ? 'light' : 'dark'} mode`}
>
	{#if theme.theme === 'dark'}
		<Sun size={20} />
	{:else}
		<Moon size={20} />
	{/if}
</Button.Root>

// src/components/ThemeToggle.tsx
import { Moon, Sun } from "lucide-react";
import { useTheme } from "@/hooks/useTheme";
import { Button } from "@/components/ui/button";

export function ThemeToggle() {
  const { theme, toggleTheme } = useTheme();

  return (
    <Button
      variant="ghost"
      size="icon"
      onClick={toggleTheme}
      className="text-muted-foreground hover:text-foreground hover:bg-muted"
      aria-label={`Switch to ${theme === "dark" ? "light" : "dark"} mode`}
    >
      {theme === "dark" ? <Sun size={20} /> : <Moon size={20} />}
    </Button>
  );
}
