// src/components/SearchFilter.tsx
import { useState } from "react";
import { Search, X } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

interface SearchFilterProps {
  onSearch: (query: string) => void;
  className?: string;
}

export function SearchFilter({ onSearch, className }: SearchFilterProps) {
  const [query, setQuery] = useState("");
  const [isExpanded, setIsExpanded] = useState(false);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSearch(query);
  };

  const handleClear = () => {
    setQuery("");
    onSearch("");
  };

  return (
    <form onSubmit={handleSubmit} className={cn("relative", className)}>
      <div className="flex items-center gap-2">
        {!isExpanded ? (
          <Button
            type="button"
            variant="ghost"
            size="icon"
            onClick={() => setIsExpanded(true)}
            className="text-muted-foreground hover:text-foreground"
          >
            <Search size={20} />
          </Button>
        ) : (
          <>
            <div className="relative flex-1">
              <Search
                size={18}
                className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground"
              />
              <Input
                type="text"
                placeholder="Search posts..."
                value={query}
                onChange={(e) => {
                  setQuery(e.target.value);
                  onSearch(e.target.value);
                }}
                className="pl-10 pr-10 bg-muted/50 border-border focus:bg-background"
                autoFocus
              />
              {query && (
                <button
                  type="button"
                  onClick={handleClear}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                >
                  <X size={16} />
                </button>
              )}
            </div>
            <Button
              type="button"
              variant="ghost"
              size="sm"
              onClick={() => {
                setIsExpanded(false);
                handleClear();
              }}
              className="text-muted-foreground"
            >
              Cancel
            </Button>
          </>
        )}
      </div>
    </form>
  );
}

// src/lib/components/SearchFilter.svelte
<script lang="ts">
	import { Search, X } from '@lucide/svelte';
	import * as Input from '$lib/components/ui/input';
	import * as Button from '$lib/components/ui/button';
	import { cn } from '$lib/utils';

	let { onSearch, class: className } = $props<{
		onSearch: (query: string) => void;
		class?: string;
	}>();

	let query = $state('');
	let isExpanded = $state(false);

	function handleSubmit(e: Event) {
		e.preventDefault();
		onSearch(query);
	}

	function handleClear() {
		query = '';
		onSearch('');
	}
</script>

<form onsubmit={handleSubmit} class={cn('relative', className)}>
	<div class="flex items-center gap-2">
		{#if !isExpanded}
			<Button.Root
				type="button"
				variant="ghost"
				size="icon"
				onclick={() => (isExpanded = true)}
				class="text-muted-foreground hover:text-foreground"
			>
				<Search size={20} />
			</Button.Root>
		{:else}
			<div class="relative flex-1">
				<Search size={18} class="absolute top-1/2 left-3 -translate-y-1/2 text-muted-foreground" />
				<Input.Root
					type="text"
					placeholder="Search posts..."
					bind:value={query}
					oninput={() => onSearch(query)}
					class="border-border bg-muted/50 pr-10 pl-10 focus:bg-background"
					autofocus
				/>
				{#if query}
					<button
						type="button"
						onclick={handleClear}
						class="absolute top-1/2 right-3 -translate-y-1/2 text-muted-foreground hover:text-foreground"
					>
						<X size={16} />
					</button>
				{/if}
			</div>
			<Button.Root
				type="button"
				variant="ghost"
				size="sm"
				onclick={() => {
					isExpanded = false;
					handleClear();
				}}
				class="text-muted-foreground"
			>
				Cancel
			</Button.Root>
		{/if}
	</div>
</form>
